// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxI1QQQl1KodxCbudTAlI-ntrl24pmf9Q',
    appId: '1:512397496738:web:3bf4a153d96960ee6ba2fb',
    messagingSenderId: '512397496738',
    projectId: 'meals-app-bc5a0',
    authDomain: 'meals-app-bc5a0.firebaseapp.com',
    storageBucket: 'meals-app-bc5a0.appspot.com',
    measurementId: 'G-5R3WEJ1MR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPUfvzs5ty9HWYA70qp93r4N8xQ9t-c8',
    appId: '1:512397496738:android:973fc9c68f8c9d4c6ba2fb',
    messagingSenderId: '512397496738',
    projectId: 'meals-app-bc5a0',
    storageBucket: 'meals-app-bc5a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDesTDUKsJsgWjzBkFMMAWqklnmGSrtOUI',
    appId: '1:512397496738:ios:0f823487a4830f276ba2fb',
    messagingSenderId: '512397496738',
    projectId: 'meals-app-bc5a0',
    storageBucket: 'meals-app-bc5a0.appspot.com',
    iosClientId: '512397496738-b0rfcrlag7e41olt284mdqlm4ap8ebsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDesTDUKsJsgWjzBkFMMAWqklnmGSrtOUI',
    appId: '1:512397496738:ios:0f823487a4830f276ba2fb',
    messagingSenderId: '512397496738',
    projectId: 'meals-app-bc5a0',
    storageBucket: 'meals-app-bc5a0.appspot.com',
    iosClientId: '512397496738-b0rfcrlag7e41olt284mdqlm4ap8ebsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxI1QQQl1KodxCbudTAlI-ntrl24pmf9Q',
    appId: '1:512397496738:web:63682eeb6780561a6ba2fb',
    messagingSenderId: '512397496738',
    projectId: 'meals-app-bc5a0',
    authDomain: 'meals-app-bc5a0.firebaseapp.com',
    storageBucket: 'meals-app-bc5a0.appspot.com',
    measurementId: 'G-4CN83MX5BC',
  );
}
